<?php

/*
 * Branding configs for your application
 */
return [
    'login' => [
        'page_title' => 'Login',
        'headline' => 'Login',
        'subheadline' => 'Entre na sua conta abaixo',
        'show_subheadline' => true,
        'email_address' => 'Email ',
        'password' => 'Senha',
        'edit' => 'Editar',
        'button' => 'Continue',
        'forget_password' => 'Esqueceu sua Senha?',
        'dont_have_an_account' => 'Não tem uma conta?',
        'sign_up' => 'Cadastre-se',
        'social_auth_authenticated_message' => 'Você foi autenticado via __social_providers_list__. Por favor, faça login na rede abaixo.',
        'change_email' => 'Alterar e-mail',
    ],
    'register' => [
        'page_title' => 'Registrar',
        'headline' => 'Registrar',
        'subheadline' => 'Crie sua conta gratuita abaixo.',
        'show_subheadline' => true,
        'name' => 'Nome',
        'email_address' => 'Email ',
        'password' => 'Senha',
        'password_confirmation' => 'Confirmar Senha',
        'already_have_an_account' => 'Já tem uma conta?',
        'sign_in' => 'Login',
        'button' => 'Continue',
    ],
    'verify' => [
        'page_title' => 'Verifique sua conta',
        'headline' => 'Verifique seu endereço de e-mail',
        'subheadline' => 'Antes de prosseguir, você deve verificar seu e-mail.',
        'show_subheadline' => true,
        'description' => 'Antes de prosseguir, verifique seu e-mail para obter um link de verificação. Se você não recebeu o e-mail,',
        'new_request_link' => 'clique aqui para solicitar outro',
        'new_link_sent' => 'Um novo link foi enviado para seu endereço de e-mail.',
        'or' => 'Ou',
        'logout' => 'clique aqui para sair',
    ],
    'passwordConfirm' => [
        'page_title' => 'Confirme sua senha',
        'headline' => 'Confirmar Senha',
        'subheadline' => 'Não se esqueça de confirmar sua senha abaixo',
        'show_subheadline' => true,
        'password' => 'Senha',
        'button' => 'Confirmar Senha',
    ],
    'passwordResetRequest' => [
        'page_title' => 'Solicitar uma redefinição de senha',
        'headline' => 'Redefinir senha',
        'subheadline' => 'Insira seu e-mail abaixo para redefinir sua senha',
        'show_subheadline' => true,
        'email' => 'Email ',
        'button' => 'Enviar link para redefinir a senha',
        'or' => 'ou',
        'return_to_login' => 'retornar ao login',
    ],
    'passwordReset' => [
        'page_title' => 'Redefinir sua senha',
        'headline' => 'Redefinir senha',
        'subheadline' => 'Redefina sua senha abaixo',
        'show_subheadline' => true,
        'email' => 'Email ',
        'password' => 'Senha',
        'password_confirm' => 'Confirmar Senha',
        'button' => 'Redefinir senha',
    ],
    'twoFactorChallenge' => [
        'page_title' => 'Two Factor Challenge',
        'headline_auth' => 'Authentication Code',
        'subheadline_auth' => 'Enter the authentication code provided by your authenticator application.',
        'show_subheadline_auth' => false,
        'headline_recovery' => 'Recovery Code',
        'subheadline_recovery' => 'Please confirm access to your account by entering one of your emergency recovery codes.',
        'show_subheadline_recovery' => false,
    ],

];
